" Generated from $ISABELLE_HOME/etc/symbols: show Isabelle symbols as Unicode (conceal).
syn match isabelleSymbol "\\<zero>" conceal cchar=𝟬 containedin=ALL
syn match isabelleSymbol "\\<one>" conceal cchar=𝟭 containedin=ALL
syn match isabelleSymbol "\\<two>" conceal cchar=𝟮 containedin=ALL
syn match isabelleSymbol "\\<three>" conceal cchar=𝟯 containedin=ALL
syn match isabelleSymbol "\\<four>" conceal cchar=𝟰 containedin=ALL
syn match isabelleSymbol "\\<five>" conceal cchar=𝟱 containedin=ALL
syn match isabelleSymbol "\\<six>" conceal cchar=𝟲 containedin=ALL
syn match isabelleSymbol "\\<seven>" conceal cchar=𝟳 containedin=ALL
syn match isabelleSymbol "\\<eight>" conceal cchar=𝟴 containedin=ALL
syn match isabelleSymbol "\\<nine>" conceal cchar=𝟵 containedin=ALL
syn match isabelleSymbol "\\<A>" conceal cchar=𝒜 containedin=ALL
syn match isabelleSymbol "\\<B>" conceal cchar=ℬ containedin=ALL
syn match isabelleSymbol "\\<C>" conceal cchar=𝒞 containedin=ALL
syn match isabelleSymbol "\\<D>" conceal cchar=𝒟 containedin=ALL
syn match isabelleSymbol "\\<E>" conceal cchar=ℰ containedin=ALL
syn match isabelleSymbol "\\<F>" conceal cchar=ℱ containedin=ALL
syn match isabelleSymbol "\\<G>" conceal cchar=𝒢 containedin=ALL
syn match isabelleSymbol "\\<H>" conceal cchar=ℋ containedin=ALL
syn match isabelleSymbol "\\<I>" conceal cchar=ℐ containedin=ALL
syn match isabelleSymbol "\\<J>" conceal cchar=𝒥 containedin=ALL
syn match isabelleSymbol "\\<K>" conceal cchar=𝒦 containedin=ALL
syn match isabelleSymbol "\\<L>" conceal cchar=ℒ containedin=ALL
syn match isabelleSymbol "\\<M>" conceal cchar=ℳ containedin=ALL
syn match isabelleSymbol "\\<N>" conceal cchar=𝒩 containedin=ALL
syn match isabelleSymbol "\\<O>" conceal cchar=𝒪 containedin=ALL
syn match isabelleSymbol "\\<P>" conceal cchar=𝒫 containedin=ALL
syn match isabelleSymbol "\\<Q>" conceal cchar=𝒬 containedin=ALL
syn match isabelleSymbol "\\<R>" conceal cchar=ℛ containedin=ALL
syn match isabelleSymbol "\\<S>" conceal cchar=𝒮 containedin=ALL
syn match isabelleSymbol "\\<T>" conceal cchar=𝒯 containedin=ALL
syn match isabelleSymbol "\\<U>" conceal cchar=𝒰 containedin=ALL
syn match isabelleSymbol "\\<V>" conceal cchar=𝒱 containedin=ALL
syn match isabelleSymbol "\\<W>" conceal cchar=𝒲 containedin=ALL
syn match isabelleSymbol "\\<X>" conceal cchar=𝒳 containedin=ALL
syn match isabelleSymbol "\\<Y>" conceal cchar=𝒴 containedin=ALL
syn match isabelleSymbol "\\<Z>" conceal cchar=𝒵 containedin=ALL
syn match isabelleSymbol "\\<a>" conceal cchar=𝖺 containedin=ALL
syn match isabelleSymbol "\\<b>" conceal cchar=𝖻 containedin=ALL
syn match isabelleSymbol "\\<c>" conceal cchar=𝖼 containedin=ALL
syn match isabelleSymbol "\\<d>" conceal cchar=𝖽 containedin=ALL
syn match isabelleSymbol "\\<e>" conceal cchar=𝖾 containedin=ALL
syn match isabelleSymbol "\\<f>" conceal cchar=𝖿 containedin=ALL
syn match isabelleSymbol "\\<g>" conceal cchar=𝗀 containedin=ALL
syn match isabelleSymbol "\\<h>" conceal cchar=𝗁 containedin=ALL
syn match isabelleSymbol "\\<i>" conceal cchar=𝗂 containedin=ALL
syn match isabelleSymbol "\\<j>" conceal cchar=𝗃 containedin=ALL
syn match isabelleSymbol "\\<k>" conceal cchar=𝗄 containedin=ALL
syn match isabelleSymbol "\\<l>" conceal cchar=𝗅 containedin=ALL
syn match isabelleSymbol "\\<m>" conceal cchar=𝗆 containedin=ALL
syn match isabelleSymbol "\\<n>" conceal cchar=𝗇 containedin=ALL
syn match isabelleSymbol "\\<o>" conceal cchar=𝗈 containedin=ALL
syn match isabelleSymbol "\\<p>" conceal cchar=𝗉 containedin=ALL
syn match isabelleSymbol "\\<q>" conceal cchar=𝗊 containedin=ALL
syn match isabelleSymbol "\\<r>" conceal cchar=𝗋 containedin=ALL
syn match isabelleSymbol "\\<s>" conceal cchar=𝗌 containedin=ALL
syn match isabelleSymbol "\\<t>" conceal cchar=𝗍 containedin=ALL
syn match isabelleSymbol "\\<u>" conceal cchar=𝗎 containedin=ALL
syn match isabelleSymbol "\\<v>" conceal cchar=𝗏 containedin=ALL
syn match isabelleSymbol "\\<w>" conceal cchar=𝗐 containedin=ALL
syn match isabelleSymbol "\\<x>" conceal cchar=𝗑 containedin=ALL
syn match isabelleSymbol "\\<y>" conceal cchar=𝗒 containedin=ALL
syn match isabelleSymbol "\\<z>" conceal cchar=𝗓 containedin=ALL
syn match isabelleSymbol "\\<AA>" conceal cchar=𝔄 containedin=ALL
syn match isabelleSymbol "\\<BB>" conceal cchar=𝔅 containedin=ALL
syn match isabelleSymbol "\\<CC>" conceal cchar=ℭ containedin=ALL
syn match isabelleSymbol "\\<DD>" conceal cchar=𝔇 containedin=ALL
syn match isabelleSymbol "\\<EE>" conceal cchar=𝔈 containedin=ALL
syn match isabelleSymbol "\\<FF>" conceal cchar=𝔉 containedin=ALL
syn match isabelleSymbol "\\<GG>" conceal cchar=𝔊 containedin=ALL
syn match isabelleSymbol "\\<HH>" conceal cchar=ℌ containedin=ALL
syn match isabelleSymbol "\\<II>" conceal cchar=ℑ containedin=ALL
syn match isabelleSymbol "\\<JJ>" conceal cchar=𝔍 containedin=ALL
syn match isabelleSymbol "\\<KK>" conceal cchar=𝔎 containedin=ALL
syn match isabelleSymbol "\\<LL>" conceal cchar=𝔏 containedin=ALL
syn match isabelleSymbol "\\<MM>" conceal cchar=𝔐 containedin=ALL
syn match isabelleSymbol "\\<NN>" conceal cchar=𝔑 containedin=ALL
syn match isabelleSymbol "\\<OO>" conceal cchar=𝔒 containedin=ALL
syn match isabelleSymbol "\\<PP>" conceal cchar=𝔓 containedin=ALL
syn match isabelleSymbol "\\<QQ>" conceal cchar=𝔔 containedin=ALL
syn match isabelleSymbol "\\<RR>" conceal cchar=ℜ containedin=ALL
syn match isabelleSymbol "\\<SS>" conceal cchar=𝔖 containedin=ALL
syn match isabelleSymbol "\\<TT>" conceal cchar=𝔗 containedin=ALL
syn match isabelleSymbol "\\<UU>" conceal cchar=𝔘 containedin=ALL
syn match isabelleSymbol "\\<VV>" conceal cchar=𝔙 containedin=ALL
syn match isabelleSymbol "\\<WW>" conceal cchar=𝔚 containedin=ALL
syn match isabelleSymbol "\\<XX>" conceal cchar=𝔛 containedin=ALL
syn match isabelleSymbol "\\<YY>" conceal cchar=𝔜 containedin=ALL
syn match isabelleSymbol "\\<ZZ>" conceal cchar=ℨ containedin=ALL
syn match isabelleSymbol "\\<aa>" conceal cchar=𝔞 containedin=ALL
syn match isabelleSymbol "\\<bb>" conceal cchar=𝔟 containedin=ALL
syn match isabelleSymbol "\\<cc>" conceal cchar=𝔠 containedin=ALL
syn match isabelleSymbol "\\<dd>" conceal cchar=𝔡 containedin=ALL
syn match isabelleSymbol "\\<ee>" conceal cchar=𝔢 containedin=ALL
syn match isabelleSymbol "\\<ff>" conceal cchar=𝔣 containedin=ALL
syn match isabelleSymbol "\\<gg>" conceal cchar=𝔤 containedin=ALL
syn match isabelleSymbol "\\<hh>" conceal cchar=𝔥 containedin=ALL
syn match isabelleSymbol "\\<ii>" conceal cchar=𝔦 containedin=ALL
syn match isabelleSymbol "\\<jj>" conceal cchar=𝔧 containedin=ALL
syn match isabelleSymbol "\\<kk>" conceal cchar=𝔨 containedin=ALL
syn match isabelleSymbol "\\<ll>" conceal cchar=𝔩 containedin=ALL
syn match isabelleSymbol "\\<mm>" conceal cchar=𝔪 containedin=ALL
syn match isabelleSymbol "\\<nn>" conceal cchar=𝔫 containedin=ALL
syn match isabelleSymbol "\\<oo>" conceal cchar=𝔬 containedin=ALL
syn match isabelleSymbol "\\<pp>" conceal cchar=𝔭 containedin=ALL
syn match isabelleSymbol "\\<qq>" conceal cchar=𝔮 containedin=ALL
syn match isabelleSymbol "\\<rr>" conceal cchar=𝔯 containedin=ALL
syn match isabelleSymbol "\\<ss>" conceal cchar=𝔰 containedin=ALL
syn match isabelleSymbol "\\<tt>" conceal cchar=𝔱 containedin=ALL
syn match isabelleSymbol "\\<uu>" conceal cchar=𝔲 containedin=ALL
syn match isabelleSymbol "\\<vv>" conceal cchar=𝔳 containedin=ALL
syn match isabelleSymbol "\\<ww>" conceal cchar=𝔴 containedin=ALL
syn match isabelleSymbol "\\<xx>" conceal cchar=𝔵 containedin=ALL
syn match isabelleSymbol "\\<yy>" conceal cchar=𝔶 containedin=ALL
syn match isabelleSymbol "\\<zz>" conceal cchar=𝔷 containedin=ALL
syn match isabelleSymbol "\\<alpha>" conceal cchar=α containedin=ALL
syn match isabelleSymbol "\\<beta>" conceal cchar=β containedin=ALL
syn match isabelleSymbol "\\<gamma>" conceal cchar=γ containedin=ALL
syn match isabelleSymbol "\\<delta>" conceal cchar=δ containedin=ALL
syn match isabelleSymbol "\\<epsilon>" conceal cchar=ε containedin=ALL
syn match isabelleSymbol "\\<zeta>" conceal cchar=ζ containedin=ALL
syn match isabelleSymbol "\\<eta>" conceal cchar=η containedin=ALL
syn match isabelleSymbol "\\<theta>" conceal cchar=θ containedin=ALL
syn match isabelleSymbol "\\<iota>" conceal cchar=ι containedin=ALL
syn match isabelleSymbol "\\<kappa>" conceal cchar=κ containedin=ALL
syn match isabelleSymbol "\\<lambda>" conceal cchar=λ containedin=ALL
syn match isabelleSymbol "\\<mu>" conceal cchar=μ containedin=ALL
syn match isabelleSymbol "\\<nu>" conceal cchar=ν containedin=ALL
syn match isabelleSymbol "\\<xi>" conceal cchar=ξ containedin=ALL
syn match isabelleSymbol "\\<pi>" conceal cchar=π containedin=ALL
syn match isabelleSymbol "\\<rho>" conceal cchar=ρ containedin=ALL
syn match isabelleSymbol "\\<sigma>" conceal cchar=σ containedin=ALL
syn match isabelleSymbol "\\<tau>" conceal cchar=τ containedin=ALL
syn match isabelleSymbol "\\<upsilon>" conceal cchar=υ containedin=ALL
syn match isabelleSymbol "\\<phi>" conceal cchar=φ containedin=ALL
syn match isabelleSymbol "\\<chi>" conceal cchar=χ containedin=ALL
syn match isabelleSymbol "\\<psi>" conceal cchar=ψ containedin=ALL
syn match isabelleSymbol "\\<omega>" conceal cchar=ω containedin=ALL
syn match isabelleSymbol "\\<Gamma>" conceal cchar=Γ containedin=ALL
syn match isabelleSymbol "\\<Delta>" conceal cchar=Δ containedin=ALL
syn match isabelleSymbol "\\<Theta>" conceal cchar=Θ containedin=ALL
syn match isabelleSymbol "\\<Lambda>" conceal cchar=Λ containedin=ALL
syn match isabelleSymbol "\\<Xi>" conceal cchar=Ξ containedin=ALL
syn match isabelleSymbol "\\<Pi>" conceal cchar=Π containedin=ALL
syn match isabelleSymbol "\\<Sigma>" conceal cchar=Σ containedin=ALL
syn match isabelleSymbol "\\<Upsilon>" conceal cchar=Υ containedin=ALL
syn match isabelleSymbol "\\<Phi>" conceal cchar=Φ containedin=ALL
syn match isabelleSymbol "\\<Psi>" conceal cchar=Ψ containedin=ALL
syn match isabelleSymbol "\\<Omega>" conceal cchar=Ω containedin=ALL
syn match isabelleSymbol "\\<bbbA>" conceal cchar=𝔸 containedin=ALL
syn match isabelleSymbol "\\<bool>" conceal cchar=𝔹 containedin=ALL
syn match isabelleSymbol "\\<complex>" conceal cchar=ℂ containedin=ALL
syn match isabelleSymbol "\\<bbbD>" conceal cchar=𝔻 containedin=ALL
syn match isabelleSymbol "\\<bbbE>" conceal cchar=𝔼 containedin=ALL
syn match isabelleSymbol "\\<bbbF>" conceal cchar=𝔽 containedin=ALL
syn match isabelleSymbol "\\<bbbG>" conceal cchar=𝔾 containedin=ALL
syn match isabelleSymbol "\\<bbbH>" conceal cchar=ℍ containedin=ALL
syn match isabelleSymbol "\\<bbbI>" conceal cchar=𝕀 containedin=ALL
syn match isabelleSymbol "\\<bbbJ>" conceal cchar=𝕁 containedin=ALL
syn match isabelleSymbol "\\<bbbK>" conceal cchar=𝕂 containedin=ALL
syn match isabelleSymbol "\\<bbbL>" conceal cchar=𝕃 containedin=ALL
syn match isabelleSymbol "\\<bbbM>" conceal cchar=𝕄 containedin=ALL
syn match isabelleSymbol "\\<nat>" conceal cchar=ℕ containedin=ALL
syn match isabelleSymbol "\\<bbbO>" conceal cchar=𝕆 containedin=ALL
syn match isabelleSymbol "\\<bbbP>" conceal cchar=ℙ containedin=ALL
syn match isabelleSymbol "\\<rat>" conceal cchar=ℚ containedin=ALL
syn match isabelleSymbol "\\<real>" conceal cchar=ℝ containedin=ALL
syn match isabelleSymbol "\\<bbbS>" conceal cchar=𝕊 containedin=ALL
syn match isabelleSymbol "\\<bbbT>" conceal cchar=𝕋 containedin=ALL
syn match isabelleSymbol "\\<bbbU>" conceal cchar=𝕌 containedin=ALL
syn match isabelleSymbol "\\<bbbV>" conceal cchar=𝕍 containedin=ALL
syn match isabelleSymbol "\\<bbbW>" conceal cchar=𝕎 containedin=ALL
syn match isabelleSymbol "\\<bbbX>" conceal cchar=𝕏 containedin=ALL
syn match isabelleSymbol "\\<bbbY>" conceal cchar=𝕐 containedin=ALL
syn match isabelleSymbol "\\<int>" conceal cchar=ℤ containedin=ALL
syn match isabelleSymbol "\\<leftarrow>" conceal cchar=← containedin=ALL
syn match isabelleSymbol "\\<longleftarrow>" conceal cchar=⟵ containedin=ALL
syn match isabelleSymbol "\\<longlongleftarrow>" conceal cchar=⤎ containedin=ALL
syn match isabelleSymbol "\\<longlonglongleftarrow>" conceal cchar=⇠ containedin=ALL
syn match isabelleSymbol "\\<rightarrow>" conceal cchar=→ containedin=ALL
syn match isabelleSymbol "\\<longrightarrow>" conceal cchar=⟶ containedin=ALL
syn match isabelleSymbol "\\<longlongrightarrow>" conceal cchar=⤏ containedin=ALL
syn match isabelleSymbol "\\<longlonglongrightarrow>" conceal cchar=⇢ containedin=ALL
syn match isabelleSymbol "\\<Leftarrow>" conceal cchar=⇐ containedin=ALL
syn match isabelleSymbol "\\<Longleftarrow>" conceal cchar=⟸ containedin=ALL
syn match isabelleSymbol "\\<Lleftarrow>" conceal cchar=⇚ containedin=ALL
syn match isabelleSymbol "\\<Rightarrow>" conceal cchar=⇒ containedin=ALL
syn match isabelleSymbol "\\<Longrightarrow>" conceal cchar=⟹ containedin=ALL
syn match isabelleSymbol "\\<Rrightarrow>" conceal cchar=⇛ containedin=ALL
syn match isabelleSymbol "\\<leftrightarrow>" conceal cchar=↔ containedin=ALL
syn match isabelleSymbol "\\<longleftrightarrow>" conceal cchar=⟷ containedin=ALL
syn match isabelleSymbol "\\<Leftrightarrow>" conceal cchar=⇔ containedin=ALL
syn match isabelleSymbol "\\<Longleftrightarrow>" conceal cchar=⟺ containedin=ALL
syn match isabelleSymbol "\\<mapsto>" conceal cchar=↦ containedin=ALL
syn match isabelleSymbol "\\<longmapsto>" conceal cchar=⟼ containedin=ALL
syn match isabelleSymbol "\\<midarrow>" conceal cchar=─ containedin=ALL
syn match isabelleSymbol "\\<Midarrow>" conceal cchar=═ containedin=ALL
syn match isabelleSymbol "\\<hookleftarrow>" conceal cchar=↩ containedin=ALL
syn match isabelleSymbol "\\<hookrightarrow>" conceal cchar=↪ containedin=ALL
syn match isabelleSymbol "\\<leftharpoondown>" conceal cchar=↽ containedin=ALL
syn match isabelleSymbol "\\<rightharpoondown>" conceal cchar=⇁ containedin=ALL
syn match isabelleSymbol "\\<leftharpoonup>" conceal cchar=↼ containedin=ALL
syn match isabelleSymbol "\\<rightharpoonup>" conceal cchar=⇀ containedin=ALL
syn match isabelleSymbol "\\<rightleftharpoons>" conceal cchar=⇌ containedin=ALL
syn match isabelleSymbol "\\<leadsto>" conceal cchar=↝ containedin=ALL
syn match isabelleSymbol "\\<downharpoonleft>" conceal cchar=⇃ containedin=ALL
syn match isabelleSymbol "\\<downharpoonright>" conceal cchar=⇂ containedin=ALL
syn match isabelleSymbol "\\<upharpoonleft>" conceal cchar=↿ containedin=ALL
syn match isabelleSymbol "\\<restriction>" conceal cchar=↾ containedin=ALL
syn match isabelleSymbol "\\<Colon>" conceal cchar=∷ containedin=ALL
syn match isabelleSymbol "\\<up>" conceal cchar=↑ containedin=ALL
syn match isabelleSymbol "\\<Up>" conceal cchar=⇑ containedin=ALL
syn match isabelleSymbol "\\<down>" conceal cchar=↓ containedin=ALL
syn match isabelleSymbol "\\<Down>" conceal cchar=⇓ containedin=ALL
syn match isabelleSymbol "\\<updown>" conceal cchar=↕ containedin=ALL
syn match isabelleSymbol "\\<Updown>" conceal cchar=⇕ containedin=ALL
syn match isabelleSymbol "\\<langle>" conceal cchar=⟨ containedin=ALL
syn match isabelleSymbol "\\<rangle>" conceal cchar=⟩ containedin=ALL
syn match isabelleSymbol "\\<llangle>" conceal cchar=⟪ containedin=ALL
syn match isabelleSymbol "\\<rrangle>" conceal cchar=⟫ containedin=ALL
syn match isabelleSymbol "\\<lceil>" conceal cchar=⌈ containedin=ALL
syn match isabelleSymbol "\\<rceil>" conceal cchar=⌉ containedin=ALL
syn match isabelleSymbol "\\<lfloor>" conceal cchar=⌊ containedin=ALL
syn match isabelleSymbol "\\<rfloor>" conceal cchar=⌋ containedin=ALL
syn match isabelleSymbol "\\<lparr>" conceal cchar=⦇ containedin=ALL
syn match isabelleSymbol "\\<rparr>" conceal cchar=⦈ containedin=ALL
syn match isabelleSymbol "\\<lbrakk>" conceal cchar=⟦ containedin=ALL
syn match isabelleSymbol "\\<rbrakk>" conceal cchar=⟧ containedin=ALL
syn match isabelleSymbol "\\<lbrace>" conceal cchar=⦃ containedin=ALL
syn match isabelleSymbol "\\<rbrace>" conceal cchar=⦄ containedin=ALL
syn match isabelleSymbol "\\<lblot>" conceal cchar=⦉ containedin=ALL
syn match isabelleSymbol "\\<rblot>" conceal cchar=⦊ containedin=ALL
syn match isabelleSymbol "\\<guillemotleft>" conceal cchar=« containedin=ALL
syn match isabelleSymbol "\\<guillemotright>" conceal cchar=» containedin=ALL
syn match isabelleSymbol "\\<bottom>" conceal cchar=⊥ containedin=ALL
syn match isabelleSymbol "\\<top>" conceal cchar=⊤ containedin=ALL
syn match isabelleSymbol "\\<and>" conceal cchar=∧ containedin=ALL
syn match isabelleSymbol "\\<And>" conceal cchar=⋀ containedin=ALL
syn match isabelleSymbol "\\<or>" conceal cchar=∨ containedin=ALL
syn match isabelleSymbol "\\<Or>" conceal cchar=⋁ containedin=ALL
syn match isabelleSymbol "\\<forall>" conceal cchar=∀ containedin=ALL
syn match isabelleSymbol "\\<exists>" conceal cchar=∃ containedin=ALL
syn match isabelleSymbol "\\<nexists>" conceal cchar=∄ containedin=ALL
syn match isabelleSymbol "\\<not>" conceal cchar=¬ containedin=ALL
syn match isabelleSymbol "\\<circle>" conceal cchar=○ containedin=ALL
syn match isabelleSymbol "\\<box>" conceal cchar=□ containedin=ALL
syn match isabelleSymbol "\\<diamond>" conceal cchar=◇ containedin=ALL
syn match isabelleSymbol "\\<diamondop>" conceal cchar=⋄ containedin=ALL
syn match isabelleSymbol "\\<turnstile>" conceal cchar=⊢ containedin=ALL
syn match isabelleSymbol "\\<Turnstile>" conceal cchar=⊨ containedin=ALL
syn match isabelleSymbol "\\<tturnstile>" conceal cchar=⊩ containedin=ALL
syn match isabelleSymbol "\\<TTurnstile>" conceal cchar=⊫ containedin=ALL
syn match isabelleSymbol "\\<stileturn>" conceal cchar=⊣ containedin=ALL
syn match isabelleSymbol "\\<surd>" conceal cchar=√ containedin=ALL
syn match isabelleSymbol "\\<le>" conceal cchar=≤ containedin=ALL
syn match isabelleSymbol "\\<ge>" conceal cchar=≥ containedin=ALL
syn match isabelleSymbol "\\<lless>" conceal cchar=≪ containedin=ALL
syn match isabelleSymbol "\\<ggreater>" conceal cchar=≫ containedin=ALL
syn match isabelleSymbol "\\<lesssim>" conceal cchar=≲ containedin=ALL
syn match isabelleSymbol "\\<greatersim>" conceal cchar=≳ containedin=ALL
syn match isabelleSymbol "\\<lessapprox>" conceal cchar=⪅ containedin=ALL
syn match isabelleSymbol "\\<greaterapprox>" conceal cchar=⪆ containedin=ALL
syn match isabelleSymbol "\\<in>" conceal cchar=∈ containedin=ALL
syn match isabelleSymbol "\\<notin>" conceal cchar=∉ containedin=ALL
syn match isabelleSymbol "\\<subset>" conceal cchar=⊂ containedin=ALL
syn match isabelleSymbol "\\<supset>" conceal cchar=⊃ containedin=ALL
syn match isabelleSymbol "\\<subseteq>" conceal cchar=⊆ containedin=ALL
syn match isabelleSymbol "\\<supseteq>" conceal cchar=⊇ containedin=ALL
syn match isabelleSymbol "\\<sqsubset>" conceal cchar=⊏ containedin=ALL
syn match isabelleSymbol "\\<sqsupset>" conceal cchar=⊐ containedin=ALL
syn match isabelleSymbol "\\<sqsubseteq>" conceal cchar=⊑ containedin=ALL
syn match isabelleSymbol "\\<sqsupseteq>" conceal cchar=⊒ containedin=ALL
syn match isabelleSymbol "\\<inter>" conceal cchar=∩ containedin=ALL
syn match isabelleSymbol "\\<Inter>" conceal cchar=⋂ containedin=ALL
syn match isabelleSymbol "\\<union>" conceal cchar=∪ containedin=ALL
syn match isabelleSymbol "\\<Union>" conceal cchar=⋃ containedin=ALL
syn match isabelleSymbol "\\<squnion>" conceal cchar=⊔ containedin=ALL
syn match isabelleSymbol "\\<Squnion>" conceal cchar=⨆ containedin=ALL
syn match isabelleSymbol "\\<sqinter>" conceal cchar=⊓ containedin=ALL
syn match isabelleSymbol "\\<Sqinter>" conceal cchar=⨅ containedin=ALL
syn match isabelleSymbol "\\<setminus>" conceal cchar=∖ containedin=ALL
syn match isabelleSymbol "\\<propto>" conceal cchar=∝ containedin=ALL
syn match isabelleSymbol "\\<uplus>" conceal cchar=⊎ containedin=ALL
syn match isabelleSymbol "\\<Uplus>" conceal cchar=⨄ containedin=ALL
syn match isabelleSymbol "\\<noteq>" conceal cchar=≠ containedin=ALL
syn match isabelleSymbol "\\<sim>" conceal cchar=∼ containedin=ALL
syn match isabelleSymbol "\\<doteq>" conceal cchar=≐ containedin=ALL
syn match isabelleSymbol "\\<simeq>" conceal cchar=≃ containedin=ALL
syn match isabelleSymbol "\\<approx>" conceal cchar=≈ containedin=ALL
syn match isabelleSymbol "\\<asymp>" conceal cchar=≍ containedin=ALL
syn match isabelleSymbol "\\<cong>" conceal cchar=≅ containedin=ALL
syn match isabelleSymbol "\\<smile>" conceal cchar=⌣ containedin=ALL
syn match isabelleSymbol "\\<equiv>" conceal cchar=≡ containedin=ALL
syn match isabelleSymbol "\\<frown>" conceal cchar=⌢ containedin=ALL
syn match isabelleSymbol "\\<Join>" conceal cchar=⋈ containedin=ALL
syn match isabelleSymbol "\\<bowtie>" conceal cchar=⨝ containedin=ALL
syn match isabelleSymbol "\\<prec>" conceal cchar=≺ containedin=ALL
syn match isabelleSymbol "\\<succ>" conceal cchar=≻ containedin=ALL
syn match isabelleSymbol "\\<preceq>" conceal cchar=≼ containedin=ALL
syn match isabelleSymbol "\\<succeq>" conceal cchar=≽ containedin=ALL
syn match isabelleSymbol "\\<parallel>" conceal cchar=∥ containedin=ALL
syn match isabelleSymbol "\\<Parallel>" conceal cchar=‖ containedin=ALL
syn match isabelleSymbol "\\<interleave>" conceal cchar=⫴ containedin=ALL
syn match isabelleSymbol "\\<sslash>" conceal cchar=⫽ containedin=ALL
syn match isabelleSymbol "\\<bar>" conceal cchar=¦ containedin=ALL
syn match isabelleSymbol "\\<bbar>" conceal cchar=⫿ containedin=ALL
syn match isabelleSymbol "\\<plusminus>" conceal cchar=± containedin=ALL
syn match isabelleSymbol "\\<minusplus>" conceal cchar=∓ containedin=ALL
syn match isabelleSymbol "\\<times>" conceal cchar=× containedin=ALL
syn match isabelleSymbol "\\<div>" conceal cchar=÷ containedin=ALL
syn match isabelleSymbol "\\<cdot>" conceal cchar=⋅ containedin=ALL
syn match isabelleSymbol "\\<star>" conceal cchar=⋆ containedin=ALL
syn match isabelleSymbol "\\<bullet>" conceal cchar=∙ containedin=ALL
syn match isabelleSymbol "\\<circ>" conceal cchar=∘ containedin=ALL
syn match isabelleSymbol "\\<dagger>" conceal cchar=† containedin=ALL
syn match isabelleSymbol "\\<ddagger>" conceal cchar=‡ containedin=ALL
syn match isabelleSymbol "\\<lhd>" conceal cchar=⊲ containedin=ALL
syn match isabelleSymbol "\\<rhd>" conceal cchar=⊳ containedin=ALL
syn match isabelleSymbol "\\<unlhd>" conceal cchar=⊴ containedin=ALL
syn match isabelleSymbol "\\<unrhd>" conceal cchar=⊵ containedin=ALL
syn match isabelleSymbol "\\<triangleleft>" conceal cchar=◃ containedin=ALL
syn match isabelleSymbol "\\<triangleright>" conceal cchar=▹ containedin=ALL
syn match isabelleSymbol "\\<triangle>" conceal cchar=△ containedin=ALL
syn match isabelleSymbol "\\<triangleq>" conceal cchar=≜ containedin=ALL
syn match isabelleSymbol "\\<oplus>" conceal cchar=⊕ containedin=ALL
syn match isabelleSymbol "\\<Oplus>" conceal cchar=⨁ containedin=ALL
syn match isabelleSymbol "\\<otimes>" conceal cchar=⊗ containedin=ALL
syn match isabelleSymbol "\\<Otimes>" conceal cchar=⨂ containedin=ALL
syn match isabelleSymbol "\\<odot>" conceal cchar=⊙ containedin=ALL
syn match isabelleSymbol "\\<Odot>" conceal cchar=⨀ containedin=ALL
syn match isabelleSymbol "\\<ominus>" conceal cchar=⊖ containedin=ALL
syn match isabelleSymbol "\\<oslash>" conceal cchar=⊘ containedin=ALL
syn match isabelleSymbol "\\<dots>" conceal cchar=… containedin=ALL
syn match isabelleSymbol "\\<cdots>" conceal cchar=⋯ containedin=ALL
syn match isabelleSymbol "\\<Sum>" conceal cchar=∑ containedin=ALL
syn match isabelleSymbol "\\<Prod>" conceal cchar=∏ containedin=ALL
syn match isabelleSymbol "\\<Coprod>" conceal cchar=∐ containedin=ALL
syn match isabelleSymbol "\\<infinity>" conceal cchar=∞ containedin=ALL
syn match isabelleSymbol "\\<integral>" conceal cchar=∫ containedin=ALL
syn match isabelleSymbol "\\<ointegral>" conceal cchar=∮ containedin=ALL
syn match isabelleSymbol "\\<clubsuit>" conceal cchar=♣ containedin=ALL
syn match isabelleSymbol "\\<diamondsuit>" conceal cchar=♢ containedin=ALL
syn match isabelleSymbol "\\<heartsuit>" conceal cchar=♡ containedin=ALL
syn match isabelleSymbol "\\<spadesuit>" conceal cchar=♠ containedin=ALL
syn match isabelleSymbol "\\<aleph>" conceal cchar=ℵ containedin=ALL
syn match isabelleSymbol "\\<emptyset>" conceal cchar=∅ containedin=ALL
syn match isabelleSymbol "\\<nabla>" conceal cchar=∇ containedin=ALL
syn match isabelleSymbol "\\<partial>" conceal cchar=∂ containedin=ALL
syn match isabelleSymbol "\\<flat>" conceal cchar=♭ containedin=ALL
syn match isabelleSymbol "\\<natural>" conceal cchar=♮ containedin=ALL
syn match isabelleSymbol "\\<sharp>" conceal cchar=♯ containedin=ALL
syn match isabelleSymbol "\\<angle>" conceal cchar=∠ containedin=ALL
syn match isabelleSymbol "\\<copyright>" conceal cchar=© containedin=ALL
syn match isabelleSymbol "\\<registered>" conceal cchar=® containedin=ALL
syn match isabelleSymbol "\\<hyphen>" conceal cchar=‐ containedin=ALL
syn match isabelleSymbol "\\<inverse>" conceal cchar=¯ containedin=ALL
syn match isabelleSymbol "\\<sqdot>" conceal cchar=· containedin=ALL
syn match isabelleSymbol "\\<onequarter>" conceal cchar=¼ containedin=ALL
syn match isabelleSymbol "\\<onehalf>" conceal cchar=½ containedin=ALL
syn match isabelleSymbol "\\<threequarters>" conceal cchar=¾ containedin=ALL
syn match isabelleSymbol "\\<ordfeminine>" conceal cchar=ª containedin=ALL
syn match isabelleSymbol "\\<ordmasculine>" conceal cchar=º containedin=ALL
syn match isabelleSymbol "\\<section>" conceal cchar=§ containedin=ALL
syn match isabelleSymbol "\\<paragraph>" conceal cchar=¶ containedin=ALL
syn match isabelleSymbol "\\<exclamdown>" conceal cchar=¡ containedin=ALL
syn match isabelleSymbol "\\<questiondown>" conceal cchar=¿ containedin=ALL
syn match isabelleSymbol "\\<euro>" conceal cchar=€ containedin=ALL
syn match isabelleSymbol "\\<pounds>" conceal cchar=£ containedin=ALL
syn match isabelleSymbol "\\<yen>" conceal cchar=¥ containedin=ALL
syn match isabelleSymbol "\\<cent>" conceal cchar=¢ containedin=ALL
syn match isabelleSymbol "\\<currency>" conceal cchar=¤ containedin=ALL
syn match isabelleSymbol "\\<degree>" conceal cchar=° containedin=ALL
syn match isabelleSymbol "\\<amalg>" conceal cchar=⨿ containedin=ALL
syn match isabelleSymbol "\\<mho>" conceal cchar=℧ containedin=ALL
syn match isabelleSymbol "\\<lozenge>" conceal cchar=◊ containedin=ALL
syn match isabelleSymbol "\\<wp>" conceal cchar=℘ containedin=ALL
syn match isabelleSymbol "\\<wrong>" conceal cchar=≀ containedin=ALL
syn match isabelleSymbol "\\<acute>" conceal cchar=´ containedin=ALL
syn match isabelleSymbol "\\<index>" conceal cchar=ı containedin=ALL
syn match isabelleSymbol "\\<dieresis>" conceal cchar=¨ containedin=ALL
syn match isabelleSymbol "\\<cedilla>" conceal cchar=¸ containedin=ALL
syn match isabelleSymbol "\\<hungarumlaut>" conceal cchar=˝ containedin=ALL
syn match isabelleSymbol "\\<bind>" conceal cchar=⤜ containedin=ALL
syn match isabelleSymbol "\\<then>" conceal cchar=⪢ containedin=ALL
syn match isabelleSymbol "\\<some>" conceal cchar=ϵ containedin=ALL
syn match isabelleSymbol "\\<Zcomp>" conceal cchar=⨾ containedin=ALL
syn match isabelleSymbol "\\<Zinj>" conceal cchar=↣ containedin=ALL
syn match isabelleSymbol "\\<Zpinj>" conceal cchar=⤔ containedin=ALL
syn match isabelleSymbol "\\<Zfinj>" conceal cchar=⤕ containedin=ALL
syn match isabelleSymbol "\\<Zsurj>" conceal cchar=↠ containedin=ALL
syn match isabelleSymbol "\\<Zpsurj>" conceal cchar=⤀ containedin=ALL
syn match isabelleSymbol "\\<Zbij>" conceal cchar=⤖ containedin=ALL
syn match isabelleSymbol "\\<Zpfun>" conceal cchar=⇸ containedin=ALL
syn match isabelleSymbol "\\<Zffun>" conceal cchar=⇻ containedin=ALL
syn match isabelleSymbol "\\<Zdres>" conceal cchar=◁ containedin=ALL
syn match isabelleSymbol "\\<Zndres>" conceal cchar=⩤ containedin=ALL
syn match isabelleSymbol "\\<Zrres>" conceal cchar=▷ containedin=ALL
syn match isabelleSymbol "\\<Znrres>" conceal cchar=⩥ containedin=ALL
syn match isabelleSymbol "\\<Zspot>" conceal cchar=⦁ containedin=ALL
syn match isabelleSymbol "\\<Zsemi>" conceal cchar=⨟ containedin=ALL
syn match isabelleSymbol "\\<Zproject>" conceal cchar=⨡ containedin=ALL
syn match isabelleSymbol "\\<Ztypecolon>" conceal cchar=⦂ containedin=ALL
syn match isabelleSymbol "\\<Zhide>" conceal cchar=⧹ containedin=ALL
syn match isabelleSymbol "\\<Zcat>" conceal cchar=⁀ containedin=ALL
syn match isabelleSymbol "\\<Zinbag>" conceal cchar=⋿ containedin=ALL
syn match isabelleSymbol "\\<Zprime>" conceal cchar=′ containedin=ALL
syn match isabelleSymbol "\\<hole>" conceal cchar=⌑ containedin=ALL
syn match isabelleSymbol "\\<newline>" conceal cchar=⏎ containedin=ALL
syn match isabelleSymbol "\\<comment>" conceal cchar=― containedin=ALL
syn match isabelleSymbol "\\<\^cancel>" conceal cchar=⌦ containedin=ALL
syn match isabelleSymbol "\\<\^marker>" conceal cchar=✐ containedin=ALL
syn match isabelleSymbol "\\<checkmark>" conceal cchar=✓ containedin=ALL
syn match isabelleSymbol "\\<crossmark>" conceal cchar=✗ containedin=ALL
syn match isabelleSymbol "\\<open>" conceal cchar=‹ containedin=ALL
syn match isabelleSymbol "\\<close>" conceal cchar=› containedin=ALL
syn match isabelleSymbol "\\<\^here>" conceal cchar=⌂ containedin=ALL
syn match isabelleSymbol "\\<\^undefined>" conceal cchar=❖ containedin=ALL
syn match isabelleSymbol "\\<\^noindent>" conceal cchar=⇤ containedin=ALL
syn match isabelleSymbol "\\<\^smallskip>" conceal cchar=┈ containedin=ALL
syn match isabelleSymbol "\\<\^medskip>" conceal cchar=┉ containedin=ALL
syn match isabelleSymbol "\\<\^bigskip>" conceal cchar=━ containedin=ALL
syn match isabelleSymbol "\\<\^item>" conceal cchar=▪ containedin=ALL
syn match isabelleSymbol "\\<\^enum>" conceal cchar=▸ containedin=ALL
syn match isabelleSymbol "\\<\^descr>" conceal cchar=➧ containedin=ALL
syn match isabelleSymbol "\\<\^footnote>" conceal cchar=⁋ containedin=ALL
syn match isabelleSymbol "\\<\^verbatim>" conceal cchar=▩ containedin=ALL
syn match isabelleSymbol "\\<\^theory_text>" conceal cchar=⬚ containedin=ALL
syn match isabelleSymbol "\\<\^emph>" conceal cchar=∗ containedin=ALL
syn match isabelleSymbol "\\<\^bold>" conceal cchar=❙ containedin=ALL
syn match isabelleSymbol "\\<\^sub>" conceal cchar=⇩ containedin=ALL
syn match isabelleSymbol "\\<\^sup>" conceal cchar=⇧ containedin=ALL
syn match isabelleSymbol "\\<\^bsub>" conceal cchar=⇘ containedin=ALL
syn match isabelleSymbol "\\<\^esub>" conceal cchar=⇙ containedin=ALL
syn match isabelleSymbol "\\<\^bsup>" conceal cchar=⇗ containedin=ALL
syn match isabelleSymbol "\\<\^esup>" conceal cchar=⇖ containedin=ALL
syn match isabelleSymbol "\\<\^file>" conceal cchar=🗏 containedin=ALL
syn match isabelleSymbol "\\<\^dir>" conceal cchar=🗀 containedin=ALL
syn match isabelleSymbol "\\<\^url>" conceal cchar=🌐 containedin=ALL
syn match isabelleSymbol "\\<\^doc>" conceal cchar=📓 containedin=ALL
syn match isabelleSymbol "\\<\^action>" conceal cchar=☛ containedin=ALL
hi def link isabelleSymbol Special
